require('dotenv').config(); const express=require('express'); const cors=require('cors'); const bcrypt=require('bcryptjs'); const jwt=require('jsonwebtoken'); const mysql=require('mysql2/promise');
const app=express(); app.use(cors()); app.use(express.json());
const db=mysql.createPool({host:process.env.DB_HOST||'localhost',user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'blog_platform',waitForConnections:true,connectionLimit:10});
const secret=process.env.JWT_SECRET||'change-this-secret';
function auth(req,res,next){try{const h=req.headers.authorization||''; req.user=jwt.verify(h.replace('Bearer ',''),secret); next()}catch(e){res.status(401).json({message:'Authentication required'})}}
app.get('/api/posts',async(req,res)=>{try{const [rows]=await db.query('SELECT p.*,u.name AS author FROM posts p JOIN users u ON p.user_id=u.id ORDER BY p.created_at DESC');res.json(rows)}catch(e){res.status(500).json({message:'Server error'})}});
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'All fields required'});const hash=await bcrypt.hash(password,10);const [r]=await db.query('INSERT INTO users(name,email,password) VALUES(?,?,?)',[name,email,hash]);res.status(201).json({message:'Registered',userId:r.insertId})}catch(e){res.status(400).json({message:'Email may already exist'})}});
app.post('/api/auth/login',async(req,res)=>{const [rows]=await db.query('SELECT * FROM users WHERE email=?',[req.body.email]);if(!rows[0]||!(await bcrypt.compare(req.body.password,rows[0].password)))return res.status(401).json({message:'Invalid credentials'});const token=jwt.sign({id:rows[0].id,name:rows[0].name},secret,{expiresIn:'7d'});res.json({token,user:{id:rows[0].id,name:rows[0].name,email:rows[0].email})});});
app.post('/api/posts',auth,async(req,res)=>{const {title,content}=req.body;if(!title||!content)return res.status(400).json({message:'Title and content required'});const [r]=await db.query('INSERT INTO posts(user_id,title,content) VALUES(?,?,?)',[req.user.id,title,content]);res.status(201).json({id:r.insertId,message:'Post created'})});
app.put('/api/posts/:id',auth,async(req,res)=>{const [r]=await db.query('UPDATE posts SET title=?,content=? WHERE id=? AND user_id=?',[req.body.title,req.body.content,req.params.id,req.user.id]);res.json({message:r.affectedRows?'Post updated':'Post not found'})});
app.delete('/api/posts/:id',auth,async(req,res)=>{const [r]=await db.query('DELETE FROM posts WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json({message:r.affectedRows?'Post deleted':'Post not found'})});
app.get('/api/posts/:id/comments',async(req,res)=>{const [rows]=await db.query('SELECT c.*,u.name AS author FROM comments c JOIN users u ON c.user_id=u.id WHERE c.post_id=? ORDER BY c.created_at',[req.params.id]);res.json(rows)});
app.post('/api/posts/:id/comments',auth,async(req,res)=>{if(!req.body.content)return res.status(400).json({message:'Comment required'});const [r]=await db.query('INSERT INTO comments(post_id,user_id,content) VALUES(?,?,?)',[req.params.id,req.user.id,req.body.content]);res.status(201).json({id:r.insertId,message:'Comment added'})});
app.delete('/api/comments/:id',auth,async(req,res)=>{const [r]=await db.query('DELETE FROM comments WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json({message:r.affectedRows?'Comment deleted':'Comment not found'})});
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'Blog Platform API'})); const PORT=process.env.PORT||5000; app.listen(PORT,()=>console.log('Blog API running on '+PORT));