require('dotenv').config();
const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),mysql=require('mysql2/promise');
const app=express(); app.use(cors()); app.use(express.json());
const pool=mysql.createPool({host:process.env.DB_HOST||'localhost',user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'ecommerce_db',waitForConnections:true,connectionLimit:10});
const secret=process.env.JWT_SECRET||'change-this-secret';
function auth(req,res,next){try{const h=req.headers.authorization||'';req.user=jwt.verify(h.replace('Bearer ',''),secret);next()}catch(e){res.status(401).json({message:'Unauthorized'})}}
function admin(req,res,next){if(req.user.role!=='ADMIN')return res.status(403).json({message:'Admin only'});next()}
app.get('/api/products',async(req,res)=>{try{const [rows]=await pool.query('SELECT * FROM products ORDER BY id DESC');res.json(rows)}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'All fields required'});const hash=await bcrypt.hash(password,10);const [r]=await pool.query('INSERT INTO users(name,email,password) VALUES(?,?,?)',[name,email,hash]);res.status(201).json({id:r.insertId,message:'Registered successfully'})}catch(e){res.status(400).json({message:'Email may already exist'})}});
app.post('/api/auth/login',async(req,res)=>{try{const [rows]=await pool.query('SELECT * FROM users WHERE email=?',[req.body.email]);if(!rows.length||!(await bcrypt.compare(req.body.password,rows[0].password)))return res.status(401).json({message:'Invalid credentials'});const u=rows[0];res.json({token:jwt.sign({id:u.id,email:u.email,role:u.role},secret,{expiresIn:'2h'}),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/products',auth,admin,async(req,res)=>{const {name,description,price,image_url,stock}=req.body;const [r]=await pool.query('INSERT INTO products(name,description,price,image_url,stock) VALUES(?,?,?,?,?)',[name,description,price,image_url,stock]);res.status(201).json({id:r.insertId})});
app.put('/api/products/:id',auth,admin,async(req,res)=>{const {name,description,price,image_url,stock}=req.body;await pool.query('UPDATE products SET name=?,description=?,price=?,image_url=?,stock=? WHERE id=?',[name,description,price,image_url,stock,req.params.id]);res.json({message:'Product updated'})});
app.delete('/api/products/:id',auth,admin,async(req,res)=>{await pool.query('DELETE FROM products WHERE id=?',[req.params.id]);res.json({message:'Product deleted'})});
app.post('/api/orders',auth,async(req,res)=>{const {items}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({message:'Cart is empty'});const c=await pool.getConnection();try{await c.beginTransaction();let total=0;for(const i of items){const [p]=await c.query('SELECT price,stock FROM products WHERE id=? FOR UPDATE',[i.product_id]);if(!p.length||p[0].stock<i.quantity)throw new Error('Product unavailable');total+=Number(p[0].price)*i.quantity}const [o]=await c.query('INSERT INTO orders(user_id,total) VALUES(?,?)',[req.user.id,total]);for(const i of items){const [p]=await c.query('SELECT price FROM products WHERE id=?',[i.product_id]);await c.query('INSERT INTO order_items(order_id,product_id,quantity,price) VALUES(?,?,?,?)',[o.insertId,i.product_id,i.quantity,p[0].price]);await c.query('UPDATE products SET stock=stock-? WHERE id=?',[i.quantity,i.product_id])}await c.commit();res.status(201).json({orderId:o.insertId,total})}catch(e){await c.rollback();res.status(400).json({message:e.message})}finally{c.release()}});
app.get('/api/orders',auth,async(req,res)=>{const [rows]=await pool.query('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC',[req.user.id]);res.json(rows)});
app.get('/api/admin/orders',auth,admin,async(req,res)=>{const [rows]=await pool.query('SELECT o.*,u.name,u.email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC');res.json(rows)});
app.patch('/api/admin/orders/:id',auth,admin,async(req,res)=>{await pool.query('UPDATE orders SET status=? WHERE id=?',[req.body.status,req.params.id]);res.json({message:'Order status updated'})});
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'ecommerce-api'}));
const PORT=process.env.PORT||5001;app.listen(PORT,()=>console.log(`E-commerce API running on ${PORT}`));
